/**
 * As aulas do curso de Tutoriais, na ordem. Gerado junto com os vídeos
 * (C:\CLAUDE\oficinaos-tutoriais): título e descrição saem do roteiro de cada
 * aula, e a duração do próprio MP4. O arquivo é `<position com 2 dígitos>-<slug>.mp4`.
 */
import type { TutorialModule } from '@oficinaos/shared';

export interface AulaDoCurso {
  module: TutorialModule;
  slug: string;
  title: string;
  description: string;
  file: string;
  durationSeconds: number;
  position: number;
}

export const AULAS_DO_CURSO: AulaDoCurso[] = [
  {
    module: 'PRIMEIROS_PASSOS',
    slug: 'conhecendo-o-oficinaos',
    title: 'Conhecendo o OficinaOS',
    description: 'Onde fica cada coisa e o que olhar quando você abre o sistema de manhã.',
    file: '01-conhecendo-o-oficinaos.mp4',
    durationSeconds: 88,
    position: 1,
  },
  {
    module: 'PRIMEIROS_PASSOS',
    slug: 'servicos-e-precos',
    title: 'Cadastrando seus serviços e preços',
    description: 'O catálogo de mão de obra que o orçamento usa.',
    file: '02-servicos-e-precos.mp4',
    durationSeconds: 67,
    position: 2,
  },
  {
    module: 'CLIENTES',
    slug: 'cliente-e-carro',
    title: 'Cliente e carro em um minuto',
    description: 'Só o nome é obrigatório. O resto, você completa quando precisar.',
    file: '03-cliente-e-carro.mp4',
    durationSeconds: 85,
    position: 3,
  },
  {
    module: 'CLIENTES',
    slug: 'achando-pela-placa',
    title: 'Achando tudo pela placa',
    description: 'A busca rápida e o histórico de cada carro.',
    file: '04-achando-pela-placa.mp4',
    durationSeconds: 52,
    position: 4,
  },
  {
    module: 'AGENDA',
    slug: 'agenda',
    title: 'Marcar e remarcar na agenda',
    description: 'Cada mecânico com a sua coluna, e remarcar é arrastar.',
    file: '05-agenda.mp4',
    durationSeconds: 58,
    position: 5,
  },
  {
    module: 'ORDEM_DE_SERVICO',
    slug: 'abrindo-a-os',
    title: 'Abrindo a OS pela placa',
    description: 'Cliente e carro vêm preenchidos. O orçamento sai daí.',
    file: '06-abrindo-a-os.mp4',
    durationSeconds: 69,
    position: 6,
  },
  {
    module: 'ORDEM_DE_SERVICO',
    slug: 'check-in',
    title: 'Check-in com fotos e quilometragem',
    description: 'Registra como o carro chegou. Protege a oficina.',
    file: '07-check-in.mp4',
    durationSeconds: 63,
    position: 7,
  },
  {
    module: 'ORCAMENTO',
    slug: 'orcamento-por-link',
    title: 'Orçamento por link: o cliente aprova pelo celular',
    description: 'Do botão Enviar até a OS aprovada, sem ligar para ninguém.',
    file: '08-orcamento-por-link.mp4',
    durationSeconds: 86,
    position: 8,
  },
  {
    module: 'ORDEM_DE_SERVICO',
    slug: 'executar-e-avisar',
    title: 'Executar o serviço e avisar que ficou pronto',
    description: 'Cronômetro, finalização e o aviso com a mensagem pronta.',
    file: '09-executar-e-avisar.mp4',
    durationSeconds: 69,
    position: 9,
  },
  {
    module: 'ORDEM_DE_SERVICO',
    slug: 'entrega-com-assinatura',
    title: 'Entrega com assinatura do cliente',
    description: 'Quem recebeu, a km de saída e a assinatura na tela.',
    file: '10-entrega-com-assinatura.mp4',
    durationSeconds: 63,
    position: 10,
  },
  {
    module: 'DINHEIRO',
    slug: 'pix-na-hora',
    title: 'Recebendo com Pix na hora',
    description: 'O QR com o valor certo, direto para a conta da oficina.',
    file: '11-pix-na-hora.mp4',
    durationSeconds: 50,
    position: 11,
  },
  {
    module: 'PECAS',
    slug: 'pecas-e-estoque',
    title: 'Peças e estoque mínimo',
    description: 'O que tem na prateleira, o que está acabando e o que cobrar.',
    file: '12-pecas-e-estoque.mp4',
    durationSeconds: 58,
    position: 12,
  },
  {
    module: 'PECAS',
    slug: 'pesquisa-de-pecas',
    title: 'Pesquisa de peças',
    description: 'Prateleira e fornecedores lado a lado, com o preço para cobrar.',
    file: '13-pesquisa-de-pecas.mp4',
    durationSeconds: 50,
    position: 13,
  },
  {
    module: 'DINHEIRO',
    slug: 'fluxo-de-caixa',
    title: 'Fluxo de caixa e contas a receber',
    description: 'O que entrou, o que saiu e o que ainda falta receber.',
    file: '14-fluxo-de-caixa.mp4',
    durationSeconds: 57,
    position: 14,
  },
  {
    module: 'DINHEIRO',
    slug: 'comissao',
    title: 'Comissão do mecânico',
    description: 'Um percentual sobre a mão de obra, calculado sozinho.',
    file: '15-comissao.mp4',
    durationSeconds: 61,
    position: 15,
  },
  {
    module: 'FICHA_DO_CARRO',
    slug: 'ficha-do-carro',
    title: 'Ficha do carro e busca por chassi',
    description: 'O que serve em cada carro, sem abrir catálogo de fabricante.',
    file: '16-ficha-do-carro.mp4',
    durationSeconds: 51,
    position: 16,
  },
  {
    module: 'PAINEL',
    slug: 'painel-do-dia',
    title: 'O painel do dia',
    description: 'Faturamento, produção e a lista do que precisa de atenção.',
    file: '17-painel-do-dia.mp4',
    durationSeconds: 48,
    position: 17,
  },
  {
    module: 'PAINEL',
    slug: 'relatorios',
    title: 'Relatórios em PDF',
    description: 'Os números do jeito que o contador pede.',
    file: '18-relatorios.mp4',
    durationSeconds: 51,
    position: 18,
  },
  {
    module: 'POS_VENDA',
    slug: 'pos-venda',
    title: 'Pós-venda com mensagem pronta',
    description: 'Quem chamar hoje, com o texto pronto.',
    file: '19-pos-venda.mp4',
    durationSeconds: 48,
    position: 19,
  },
  {
    module: 'POS_VENDA',
    slug: 'funil',
    title: 'Funil de clientes novos',
    description: 'O orçamento que ainda não virou OS, e a ligação que não pode esfriar.',
    file: '20-funil.mp4',
    durationSeconds: 50,
    position: 20,
  },
  {
    module: 'WHATSAPP',
    slug: 'whatsapp',
    title: 'Conversas e WhatsApp oficial',
    description: 'Com a conta da própria oficina, as mensagens saem sozinhas.',
    file: '21-whatsapp.mp4',
    durationSeconds: 62,
    position: 21,
  },
  {
    module: 'CELULAR',
    slug: 'celular-do-mecanico',
    title: 'O app no celular do mecânico',
    description: 'Minhas OS: só os carros que estão com ele.',
    file: '22-celular-do-mecanico.mp4',
    durationSeconds: 52,
    position: 22,
  },
  {
    module: 'CONFIGURACOES',
    slug: 'equipe-e-papeis',
    title: 'Equipe e papéis',
    description: 'Cada pessoa com o próprio acesso, vendo só o que precisa.',
    file: '23-equipe-e-papeis.mp4',
    durationSeconds: 63,
    position: 23,
  },
  {
    module: 'CONFIGURACOES',
    slug: 'dados-da-oficina',
    title: 'Dados da oficina e Pix',
    description: 'O que aparece para o cliente, e a chave do Pix na hora.',
    file: '24-dados-da-oficina.mp4',
    durationSeconds: 64,
    position: 24,
  },
];
